name: CI/CD - Docker & Azure

env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  REPO_NAME: ${{ secrets.REPO_NAME }}
  AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}
  AZURE_RG: ${{ secrets.AZURE_RG }}
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

on:
  push:
    branches: [ main, test-ci ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:
  ci_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install black pylint pytest

      - name: Lint & Format
        run: |
          black pipeline/application_flask.py
          pylint --disable=R,C pipeline/application_flask.py || true

      - name: Run tests
        run: pytest -vv pipeline/test_model.py

  cd_pipeline:
    runs-on: ubuntu-latest
    needs: ci_pipeline

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USER }}/${{ secrets.REPO_NAME }}:latest ./pipeline

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USER }}/${{ secrets.REPO_NAME }}:latest

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        run: |
          echo "Déploiement de l'image Docker sur Azure..."
          az webapp config container set \
            --name ${{ secrets.AZURE_WEBAPP_NAME }} \
            --resource-group ${{ secrets.AZURE_RG }} \
            --docker-custom-image-name ${{ secrets.DOCKER_USER }}/${{ secrets.REPO_NAME }}:latest \
            --docker-registry-server-url https://index.docker.io \
            --docker-registry-server-user ${{ secrets.DOCKER_USER }} \
            --docker-registry-server-password ${{ secrets.DOCKER_PASSWORD }}

          az webapp deployment container config \
            --name ${{ secrets.AZURE_WEBAPP_NAME }} \
            --resource-group ${{ secrets.AZURE_RG }} \
            --enable-cd true
