name: Github-Docker Hub MLOps Pipeline

env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  REPO_NAME: ${{ secrets.REPO_NAME }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f pipeline/requirements.txt ]; then pip install -r pipeline/requirements.txt; fi

      - name: Format code
        run: black pipeline/application_flask.py

      - name: Lint code
        run: pylint --disable=R,C pipeline/application_flask.py

      - name: Run tests
        run: python -m pytest -vv pipeline/test_model.py

  cd_pipeline:
    runs-on: ubuntu-latest
    needs: ci_pipeline

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get current date for tagging
        id: date
        run: echo "DATE=$(date +'%Y-%m-%d--%H-%M-%S')" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build pipeline/ --file pipeline/Dockerfile --tag $DOCKER_USER/$REPO_NAME:$DATE

      - name: Push Docker image
        run: docker push $DOCKER_USER/$REPO_NAME:$DATE